#!/usr/bin/env bash
# =============================================================================
#  ONE-SHOT DEPLOY SCRIPT  —  Kali Linux + Nginx + Tor Hidden Service
# -----------------------------------------------------------------------------
#  Usage:   sudo ./deploy.sh
#
#  After it finishes, the app is reachable at:
#     - http://localhost
#     - http://<your-LAN-IP>
#     - http://<auto-generated>.onion   (via Tor)
#
#  This script is intentionally self-contained:
#   * installs node/nginx/tor if missing
#   * builds the Vite SPA
#   * writes its own nginx site config
#   * writes its own tor hidden-service config
#   * frees ports 80 / 8080 if something else is squatting them
#   * retries npm install / build with safe fallbacks
# =============================================================================
set -Eeuo pipefail

# ---- pretty logging ---------------------------------------------------------
c_reset=$'\e[0m'; c_b=$'\e[1m'; c_g=$'\e[32m'; c_y=$'\e[33m'; c_r=$'\e[31m'; c_c=$'\e[36m'
log()  { echo "${c_c}${c_b}==>${c_reset} $*"; }
ok()   { echo "${c_g}${c_b} ✓ ${c_reset} $*"; }
warn() { echo "${c_y}${c_b} ! ${c_reset} $*" >&2; }
die()  { echo "${c_r}${c_b} ✗ ${c_reset} $*" >&2; exit 1; }
trap 'die "deploy failed at line $LINENO (last cmd: $BASH_COMMAND)"' ERR

# ---- preconditions ----------------------------------------------------------
[[ $EUID -eq 0 ]] || die "Run as root:  sudo ./deploy.sh"

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_ROOT"
log "Project root: $PROJECT_ROOT"

# The user that owns the source tree (used so npm doesn't run as root)
BUILD_USER="${SUDO_USER:-$(logname 2>/dev/null || echo root)}"
log "Build user:  $BUILD_USER"

APP_NAME="nexuscc"
WEB_ROOT="/var/www/${APP_NAME}"
NGINX_SITE="/etc/nginx/sites-available/${APP_NAME}"
NGINX_LINK="/etc/nginx/sites-enabled/${APP_NAME}"
TOR_HS_DIR="/var/lib/tor/${APP_NAME}/"
TOR_DROPIN="/etc/tor/torrc.d/${APP_NAME}.conf"
NGINX_PORT_LAN=80      # public-facing (localhost + LAN)
NGINX_PORT_TOR=8080    # loopback-only, used by Tor

# =============================================================================
# 1. .env  ---------------------------------------------------------------------
# =============================================================================
if [[ ! -f .env ]]; then
  if [[ -f .env.example ]]; then
    cp .env.example .env
    warn ".env was missing — copied from .env.example. Edit it if you need different keys, then re-run."
  else
    die ".env not found and no .env.example to copy from."
  fi
fi
log "Loading variables from .env"
set -a; # shellcheck disable=SC1091
source .env; set +a

# =============================================================================
# 2. System packages -----------------------------------------------------------
# =============================================================================
need_pkg() { dpkg -s "$1" >/dev/null 2>&1; }

install_if_missing() {
  local missing=()
  for p in "$@"; do need_pkg "$p" || missing+=("$p"); done
  if (( ${#missing[@]} )); then
    log "Installing: ${missing[*]}"
    DEBIAN_FRONTEND=noninteractive apt-get update -y
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "${missing[@]}"
  fi
}

install_if_missing curl ca-certificates nginx tor lsof procps

# Node.js (need >=18). Install Node 20 from NodeSource if missing/too old.
need_node() {
  command -v node >/dev/null 2>&1 || return 1
  local major; major="$(node -p 'process.versions.node.split(".")[0]')"
  (( major >= 18 ))
}
if ! need_node; then
  log "Installing Node.js 20 LTS"
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs
fi
ok "node $(node -v) / npm $(npm -v)"

# =============================================================================
# 3. Free conflicting ports ----------------------------------------------------
# =============================================================================
free_port() {
  local port="$1"
  local pids
  pids="$(lsof -t -iTCP:"$port" -sTCP:LISTEN 2>/dev/null || true)"
  [[ -z "$pids" ]] && return 0
  warn "Port $port is in use by PID(s): $pids — attempting to free it"
  # If it's our own nginx, leave it; we'll reload later
  for pid in $pids; do
    local exe; exe="$(readlink -f /proc/$pid/exe 2>/dev/null || echo '')"
    if [[ "$exe" == *nginx* ]]; then
      systemctl stop nginx || true
    else
      kill "$pid" 2>/dev/null || true
    fi
  done
  sleep 1
  pids="$(lsof -t -iTCP:"$port" -sTCP:LISTEN 2>/dev/null || true)"
  [[ -z "$pids" ]] || { warn "Port $port still busy — killing -9"; kill -9 $pids || true; }
}
free_port "$NGINX_PORT_LAN"
free_port "$NGINX_PORT_TOR"

# =============================================================================
# 4. Build the SPA -------------------------------------------------------------
# =============================================================================
log "Installing npm dependencies"
run_as_build() { sudo -u "$BUILD_USER" -H bash -lc "cd '$PROJECT_ROOT' && set -a && source .env && set +a && $*"; }

if ! run_as_build "npm ci --no-audit --no-fund" 2>/tmp/${APP_NAME}-npm.log; then
  warn "npm ci failed — wiping node_modules + lockfile and retrying with npm install"
  rm -rf node_modules package-lock.json
  run_as_build "npm install --no-audit --no-fund"
fi

log "Building production bundle"
if ! run_as_build "npm run build" 2>/tmp/${APP_NAME}-build.log; then
  warn "Build failed — clearing vite cache and retrying once"
  rm -rf node_modules/.vite dist
  run_as_build "npm run build"
fi
[[ -f dist/index.html ]] || die "Build produced no dist/index.html — see /tmp/${APP_NAME}-build.log"
ok "Build OK ($(du -sh dist | cut -f1))"

# =============================================================================
# 5. Publish to web root -------------------------------------------------------
# =============================================================================
log "Publishing to $WEB_ROOT"
mkdir -p "$WEB_ROOT"
# cp -a is in coreutils; no rsync needed
rm -rf "${WEB_ROOT:?}/"*
cp -a dist/. "$WEB_ROOT/"
chown -R www-data:www-data "$WEB_ROOT"
find "$WEB_ROOT" -type d -exec chmod 755 {} \;
find "$WEB_ROOT" -type f -exec chmod 644 {} \;

# =============================================================================
# 6. Nginx site ----------------------------------------------------------------
# =============================================================================
log "Writing nginx site config"
cat > "$NGINX_SITE" <<NGINX
# Auto-generated by deploy.sh — safe to edit, will be overwritten on next deploy.

server {
    listen ${NGINX_PORT_LAN} default_server;
    listen [::]:${NGINX_PORT_LAN} default_server;
    listen 127.0.0.1:${NGINX_PORT_TOR};   # used by the Tor hidden service

    server_name _;

    root ${WEB_ROOT};
    index index.html;

    # Security headers (safe defaults for both clearnet and onion)
    add_header X-Frame-Options          "SAMEORIGIN" always;
    add_header X-Content-Type-Options   "nosniff"    always;
    add_header Referrer-Policy          "no-referrer" always;
    add_header Permissions-Policy       "geolocation=(), microphone=(), camera=()" always;

    # Hashed Vite assets — cache aggressively
    location /assets/ {
        access_log off;
        expires    1y;
        add_header Cache-Control "public, immutable";
        try_files  \$uri =404;
    }

    # SPA fallback so React Router deep-links work
    location / {
        try_files \$uri \$uri/ /index.html;
    }

    # Don't leak dotfiles
    location ~ /\.(?!well-known).* { deny all; }

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1024;
}
NGINX

# Remove the default welcome page if present
rm -f /etc/nginx/sites-enabled/default
ln -sf "$NGINX_SITE" "$NGINX_LINK"

log "Testing nginx config"
nginx -t
systemctl enable nginx >/dev/null 2>&1 || true
systemctl restart nginx
ok "nginx is up on :${NGINX_PORT_LAN} (LAN) and 127.0.0.1:${NGINX_PORT_TOR} (Tor)"

# =============================================================================
# 7. Tor hidden service --------------------------------------------------------
# =============================================================================
log "Configuring Tor hidden service"
mkdir -p /etc/tor/torrc.d
# Make sure the main torrc loads the drop-in dir (Debian/Kali default does, but be safe)
if ! grep -qE '^\s*%include\s+/etc/tor/torrc\.d/' /etc/tor/torrc 2>/dev/null; then
  echo "%include /etc/tor/torrc.d/" >> /etc/tor/torrc
fi

cat > "$TOR_DROPIN" <<TORRC
# Auto-generated by deploy.sh
HiddenServiceDir ${TOR_HS_DIR}
HiddenServiceVersion 3
HiddenServicePort 80 127.0.0.1:${NGINX_PORT_TOR}
TORRC

mkdir -p "$TOR_HS_DIR"
chown -R debian-tor:debian-tor "$TOR_HS_DIR" 2>/dev/null || chown -R tor:tor "$TOR_HS_DIR" 2>/dev/null || true
chmod 700 "$TOR_HS_DIR"

systemctl enable tor >/dev/null 2>&1 || true
systemctl restart tor

# Wait (up to 30s) for Tor to generate the hostname
log "Waiting for Tor to publish .onion hostname"
ONION=""
for i in {1..30}; do
  if [[ -s "${TOR_HS_DIR}hostname" ]]; then
    ONION="$(cat "${TOR_HS_DIR}hostname")"
    break
  fi
  sleep 1
done

# =============================================================================
# 8. Summary -------------------------------------------------------------------
# =============================================================================
LAN_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
echo
echo "${c_g}${c_b}══════════════════════════════════════════════════════════════${c_reset}"
echo "${c_g}${c_b}  DEPLOYMENT COMPLETE${c_reset}"
echo "${c_g}${c_b}══════════════════════════════════════════════════════════════${c_reset}"
echo "  Local:     ${c_b}http://localhost${c_reset}"
[[ -n "$LAN_IP" ]] && echo "  LAN:       ${c_b}http://${LAN_IP}${c_reset}"
if [[ -n "$ONION" ]]; then
  echo "  Tor:       ${c_b}http://${ONION}${c_reset}"
else
  warn "Tor hostname not yet available — check:  sudo cat ${TOR_HS_DIR}hostname"
fi
echo
echo "  Re-deploy: ${c_b}sudo ./deploy.sh${c_reset}"
echo "  Logs:      journalctl -u nginx -e   |   journalctl -u tor -e"
echo "${c_g}${c_b}══════════════════════════════════════════════════════════════${c_reset}"
